### ISSUE TITLE
No private_settings.py

### ISSUE THREAD

**Issue by carpepraedam** [unh-webappdev/FlashCourses_api#10]
### Description

I'm sure this is by design. However to avoid having contributors change manage.py settings (which would then be tracked in version control) there should be instructions to create one in README.md.

private_settings.py should be in gitignore

### Steps to Reproduce

1. manage.py runserver 

Expected behavior: local server starts at localhost:8000

Actual behavior: ImportError

Frequency: 100%

**Comment by andrea5972** [comment]
I already had version control set up a  gitignore for private_settings.py before the code was ever pushed to the main repos. We worked with version control in class, and have already started an instructionally page in the shared google file with instructions for settings. As we stated in class during the last scrum meeting.

**Comment by carpepraedam** [comment]
Great. We need those reflected in the README here. Either in the main repo README or another README in Flash_course/docs
