### ISSUE TITLE
Syntax Errors and Duplicate Import/ModelAdmin Registrations

### ISSUE THREAD

**Issue by carpepraedam** [unh-webappdev/FlashCourses_api#11]
### Description

Syntax Errors and Duplicate Import/ModelAdmin Registrations

### Steps to Reproduce

1. manage.py runserver
2. See courses/admin.py

Expected behavior: 

Server to run

Actual behavior: 

Errors thrown for syntax errors (line 9). When those are corrected errors are thrown for duplicate registrations (lines 23/24 and 28/29)

Frequency: 100%

**Comment by andrea5972** [comment]
Done.

**Comment by carpepraedam** [comment]
Closing. Resolved.
