### ISSUE TITLE
Migration Errors in flashcards

### ISSUE THREAD

**Issue by carpepraedam** [unh-webappdev/FlashCourses_api#13]
### Description

Merge conflicts causing syntax errors

### Additional Information

This is still causing headaches. Remove all migrations 000X files from all apps to reset.

**Comment by mihaelasabin** [comment]
Documentation must have instructions for 'resetting' the database to no content and no schema. 
1. remove all migrations files from all apps
2. Using mysql utility:
2.1 login with development credentials: mysql -u <username> -p
2.2 drop database if exists <db_name>

**Comment by carpepraedam** [comment]
Closing. Resolved in documentation and via server database migrations
