### ISSUE TITLE
Rest_framework is not installed

### ISSUE THREAD

**Issue by carpepraedam** [unh-webappdev/FlashCourses_api#14]
### Description

Rest_framework is not installed in settings.py. It appears to be on the master branch, so I'm not sure what is going on here.

**Comment by mce123** [comment]
This must be a version control issue. It is installed in my copy locally. Either that or my gitignore didn't upload it. Either way, Version Control should follow up and let me know what I should do, because Andrea said not to upload settings.py

**Comment by andrea5972** [comment]
We've added to our common.py and will be sending a request to version control for a push

**Comment by mce123** [comment]
Is any other action needed here?

**Comment by carpepraedam** [comment]
Closing. Resolved via PR #23
