### ISSUE TITLE
Primary keys with AutoField

### ISSUE THREAD

**Issue by mihaelasabin** [unh-webappdev/FlashCourses_api#18]
### Description

UserProfile (in accounts.models.py), Institution and Course (in courses.models.py), use AutoField for these models' primary key: user_id, ipeds, and course_id. 

### Steps to Consider

1. Decide if you let Django to create values for these primary key
2. If yes, remove these fields from their respective class definitinos
3. If not, use an appropriate Django models field and enter values for primary keys in Admin Panel (or data source to populate with data these models).

**Comment by andrea5972** [comment]
We have updated the database to include:
Course 
         course_number = models.AutoField(auto_created=True, primary_key=True)

UserProfile
         user_id = models.AutoField(auto_created=True, primary_key=True)

**Comment by mihaelasabin** [comment]
course_number cannot be of type AutoField because it's an identifier that combines letters and digits. I propose you let Django create its default primary key "id" field for the Course model. 

If you want Django to automatically add a primary key for the UserProfile, then remove the field user_id. Django will create the primary key "id" for this model, too. See Quick Example in Models https://docs.djangoproject.com/en/2.0/topics/db/models/.

**Comment by carpepraedam** [comment]
@mihaelasabin can be closed. resolved in pr #38
