### ISSUE TITLE
Add field to course model for course ID

### ISSUE THREAD

**Issue by mihaelasabin** [unh-webappdev/FlashCourses_api#19]
### Description

Course model includes course ID

### Steps to Reproduce

 Add course_id of CharField. This is not a primary IF we choose to use Django's AutoField for primary key values. 

In principle, course catalogs use course ID to uniquely identify courses in catalogs. However, old courses get removed and I'm not sure that all schools have a system that guarantees that a new course id doesn't clash with any of the courses in the history of the institution. 

I recommend we make it a non-pk field.

Expected behavior: listing courses looks like a course catalog directory

**Comment by andrea5972** [comment]
Thank you, that makes much more sense that. Aashirya and I are working on the database now, and will update the primary key to a AutoField.

**Comment by carpepraedam** [comment]
@mihaelasabin can be closed. Not sure which PR. But the requested changes are reflected as of PR #38
