### ISSUE TITLE
Name for local db.sqlite database is confusing

### ISSUE THREAD

**Issue by carpepraedam** [unh-webappdev/FlashCourses_api#54]
### Description

Not sure when this changed, but the 'NAME' keyword in the DATABASES in common.py changed to 'FlashCourse'. This will create a db.sqlite3 file named FlashCourse. This is confusing.

### Steps to Reproduce

1. migrate/make migrations

Expected behavior: db.sqlite3 to be created

Actual behavior: FlashCourse is created

### Suggested Fix

It needs to be obvious that file is a sqlite3 file. Either add a file extension so the name is "FlashCourse.sqlite3" or change it to the standard "db.sqlite3"

**Comment by carpepraedam** [comment]
for reference, this is the default setting:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

**Comment by andrea5972** [comment]
Done

**Comment by Aashirya1995** [comment]
Done!
