### ISSUE TITLE
Model UUID fields are broken.

### ISSUE THREAD

**Issue by carpepraedam** [unh-webappdev/FlashCourses_api#58]
### Description

The recent change from:
unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

to:
unique_id = models.UUIDField(default=uuid.uuid4())

Breaks the build. Because it is not a function call to uuid4() and opposed to the a reference to uuid it will get executed everytime the program is compiled. Which leads to brand new values every single time we run make migrations. This leads to django detected a model change every time, which then will be picked up by the migrations framework. 

It is needs to unique, and not editable. So we need revert back to the original:
unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

### Steps to Reproduce

Just run makemigrations a bunch of times.

1. python manage.py makemigrations X 10
2. I get 10 new migration files.

**Comment by andrea5972** [comment]
This has also been updated to the original unique_id field
