### ISSUE TITLE
No requirements.txt or README.md

### ISSUE THREAD

**Issue by carpepraedam** [unh-webappdev/FlashCourses_api#9]
### Description

No requirements.txt or README.md

### Steps to Reproduce

1. View the directory structure

Expected behavior: I should be able to pull the repo for the first as a first-time contributor and see installation instructions. This need to be in a README.md and include instructions to install dependencies listed in requirements.txt

Actual behavior: Files do not exist

**Comment by carpepraedam** [comment]
Correction: A README.md does exist at the repo root level. We also have a Flash_courses/docs directory. Either a new README in the Flash_courses/docs or installation instructions in the root level README. Probably better at the root level along with the requirements.txt

**Comment by mce123** [comment]
We just haven't finalized our documentation yet to copy it into a .md format - however we will copy what we have this week into it. People have been referring to the documentation on Google Drive for the time being. I haven't heard any complaints of people not knowing how to use the API or anything like that.

**Comment by carpepraedam** [comment]
I'm speaking in terms of installation instructions not API documentation. There should be a step by step installation explanation.

1. Install all dependencies in requirements.txt: pip install -r requirements.txt
2. Create a private_settings.py in FlashCourses/settings. Add the following:
    debug = True
    SECRET_KEY = "some long random alphanumeric string" (or set it as an environment variable which will be pulled in from common.py)
3. Run migrations: python3 manage.py migrate
4. Create a super user: python3 manage.py createsuperuser
5. Run the server: python3 manage.py runserver
6. View project at: localhost:8000

**Comment by mihaelasabin** [comment]
these are instructions that any contributor (everybody in this class and beyond) can use to re-create a development environment on their own machines in which they can run the project.

**Comment by mce123** [comment]
Thanks for the clarification!

**Comment by andrea5972** [comment]
We have created the databases requirements.txt and currently have our instructions on our google drive, but will create it as a readme.md as well

**Comment by mce123** [comment]
requirements.txt will be from the server.

**Comment by mce123** [comment]
Has this been completed? I know we created a README.md file last week, and the requirements.txt file was coming from the server because my development environment already had most of these modules installed for other projects, so I couldn't re-install them in a virtual environment and export a clean requirements.txt file for the server, so instead I gave them all of the commands to run. I know we need to update our README.md file this week, however that's pending new API endpoints from Arjun, which won't be completed until Monday night at least.

**Comment by carpepraedam** [comment]
Closing. Requirements.txt has been updated to include only packages needed for local development. No mysqlclient, no memcached, etc. Any additional package requirements can be added at the will of the individual collaborators via pip as their needs arise. 

Any additional packages deemed important enough for project wide dissemination can be suggested by opening a new issue.
